apiVersion: v1
kind: Service
metadata:
  name: new-calculator-microservice
spec:
  type: LoadBalancer
  selector:
    app: new-calculator-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
